Output format request
bird-house/birdy pull request #182
Opened 2020-10-01 15:57 UTC by f-PLT

## Overview

This PR addresses part of #163 

Changes:

* Property and function to modify the 'output' arguments used when executing a process for the client
* Added option to cli to specify output argument (list of a single tuple)

## Additional Information

For the client, it's possible to create a list of as many tuples (output_identifier, as_ref, mimetype) as one needs. For this PR I kept it simple and implemented it like the language property. The set outputs will override the automatically created outputs for each process until it's reset.

For the cli, since the number of arguments for options need to be fixed (at least from my comprehension of click.command), it's only possible to use a single output as an argument. Also, I ended up implementing an option with 3 arguments instead of a combination of flag (for `as_ref`) and single arg options because `as_ref` can be True, False or None, and using a flag removed the ability to use None (and therefore the default for a process).

2020-10-07 13:46 UTC, cehbrecht commented
@f-PLT The tests are failing because of our notebook test. Either ignore it or disable the notebook test for now. We should fix it with another PR.

2020-10-07 13:51 UTC, cehbrecht commented
@f-PLT Could you update the api docs with an example? Docs are generated from the inline documentation:
* https://github.com/bird-house/birdy/blob/master/birdy/cli/__init__.py
* https://github.com/bird-house/birdy/blob/master/docs/source/api.rst
* https://birdy.readthedocs.io/en/latest/api.html

2020-10-07 13:55 UTC, cehbrecht commented
@f-PLT I tried it with a local emu. I might have done wrong ... but didn't get what I expected (checked cli only):
```
$ birdy multiple_outputs
Output:
output=http://localhost:5000/outputs/6bc85a14-08a4-11eb-b1b7-784f435e8862/input.metalink
output_meta4=http://localhost:5000/outputs/6bc85a14-08a4-11eb-b1b7-784f435e8862/input.meta4
```

with `outputs` option:
```
birdy --outputs output True None multiple_outputs
[('output', True, None)]
    
Output:
output=http://localhost:5000/outputs/9d9f0024-08a4-11eb-b473-784f435e8862/input.metalink
output_meta4=http://localhost:5000/outputs/9d9f0024-08a4-11eb-b473-784f435e8862/input.meta4

```

2020-10-07 14:01 UTC, cehbrecht commented
@f-PLT At least for cli it looks complicated to use:
* I would expect the `--outputs` parameter as an option of the process command.
* The `birdy multiple_outputs -h` should list the possible outputs.

Maybe just specifying the output name? 
```
$ birdy multiple_outputs --outputs output
```

Currently it asks me to give all three arguments for an output:
```
$ birdy --outputs output multiple_outputs 
Error: --outputs option requires 3 arguments
```

These are things that could also be improved later ... as long we don't break things.

2020-10-07 14:02 UTC, cehbrecht requested changes
Update api docs with an example. 

See inline comments.

2020-10-07 15:16 UTC, huard commented
Often, different processes have the same name, e.g. `output`, so there is a risk of confusion by defining the `output_formats` at the class level. Also, the way the code is written, it looks like the request will include all the output_formats, even for those unrelated to a given process, generating URLs with irrelevant content. 

Another option would be to have, for each process, an optional argument `output_formats={}` holding a dictionary of `identifier: (as_ref, mime_type)`. There is a small risk of `output_formats` shadowing an actual input identifier, but this is easy to check at instantiation. In this case, we could rename the input identifier to `output_formats_` in the `sanitize` function.

2020-10-07 18:15 UTC, f-PLT commented
> @f-PLT I tried it with a local emu. I might have done wrong ... but didn't get what I expected (checked cli only):
> 
> ```
> $ birdy multiple_outputs
> Output:
> output=http://localhost:5000/outputs/6bc85a14-08a4-11eb-b1b7-784f435e8862/input.metalink
> output_meta4=http://localhost:5000/outputs/6bc85a14-08a4-11eb-b1b7-784f435e8862/input.meta4
> ```
> 
> with `outputs` option:
> 
> ```
> birdy --outputs output True None multiple_outputs
> [('output', True, None)]
>     
> Output:
> output=http://localhost:5000/outputs/9d9f0024-08a4-11eb-b473-784f435e8862/input.metalink
> output_meta4=http://localhost:5000/outputs/9d9f0024-08a4-11eb-b473-784f435e8862/input.meta4
> ```

For the above, the default value for as_ref is already set to true.

Excuting with as_ref = False will then return the 'output' output directly:
```
birdy --outputs output False None multiple_outputs

[('output', False, None)]
ProcessSucceeded  [####################################]  100%         
Output:
output=['<?xml version="1.0" encoding="UTF-8"?>\n<metalink version="3.0" xmlns="http://www.metalinker.org/" generator="PyWPS/4.2.8">\n    <identity>test-ml-1</identity>\n    <description>Testing MetaLink with text files.</description>\n\n    <files>\n        <file name="input.txt">\n            <identity>output_0</identity>\n            <size>9</size>\n            <resources>\n                <url type="http">http://localhost:5000/outputs/ae52f46f-08b0-11eb-9334-0800274cd70c/input.txt</url>\n            </resources>\n        </file>\n        <file name="input_sqj0lhfc.txt">\n            <identity>output_1</identity>\n            <size>9</size>\n            <resources>\n                <url type="http">http://localhost:5000/outputs/ae52f470-08b0-11eb-9334-0800274cd70c/input_sqj0lhfc.txt</url>\n            </resources>\n        </file>\n    </files>\n</metalink>']
output_meta4=http://localhost:5000/outputs/ae52f46e-08b0-11eb-9334-0800274cd70c/input.meta4
```

The `outputs` option is used to modify the default `as_ref` and `mimetype` values of the process, but if there's no logic inside the process handler (server side), it cannot be used to determine/limit which output is given. I think it should be doable using a single complex output that supports different mime types and having the process handler give the appropriate output.

Using only the identifier doesn't seem to change anything, just like using dummy ones; the default output definitions are used.

2020-10-07 18:30 UTC, huard commented
To test this, I suggest you modify Emu's `output_formats` process in emu/processes/wps_output_formats.py. For example, both outputs could support an alternative ZIP format, that would return a zipped version of the output.

2020-10-07 18:38 UTC, f-PLT commented
> Often, different processes have the same name, e.g. `output`, so there is a risk of confusion by defining the `output_formats` at the class level. Also, the way the code is written, it looks like the request will include all the output_formats, even for those unrelated to a given process, generating URLs with irrelevant content.
> 
> Another option would be to have, for each process, an optional argument `output_formats={}` holding a dictionary of `identifier: (as_ref, mime_type)`. There is a small risk of `output_formats` shadowing an actual input identifier, but this is easy to check at instantiation. In this case, we could rename the input identifier to `output_formats_` in the `sanitize` function.

At first I had trouble adding a generic input to all processes, but I think I figured it out. The class level approach was simpler to implement so I could test it. I'll be updating it shortly.

I'm not sure about the output_format dictionary approach though. Shouldn't a modification to the defaults either be automated, like it's already done for complex outputs , or be temporary by needing the added argument each time?

2020-10-07 20:43 UTC, huard commented
You mean like for sync vs async ? I think ideally, this would all be process based. Some process complete fast, so there is no need to have them async, while others take a lot of time. So in a given notebook, you probably want to run both async and sync processes, which at the moment requires either creating two client instances, or changing the internal state mid-way. 

Could a more elegant option be to use a `with` statement ? E.g. 
```
wps = WPSClient(url)
with wps.options(output_format={}, mode="async"):
    wps.my_process(input1=...)
```

2020-10-08 13:47 UTC, f-PLT commented
I think this would be the better approach. Still temporary and visible (can't set it, forget about it and have it cause trouble later), but easier to apply to a series of processes. That, and having the formats in a dictionary instead of a list of tuples will be easier for users.

2020-10-08 13:56 UTC, huard commented
Good ! @cehbrecht This will imply some refactoring. Are you OK with this ?

2020-10-08 18:18 UTC, cehbrecht commented
> You mean like for sync vs async ? I think ideally, this would all be process based. Some process complete fast, so there is no need to have them async, while others take a lot of time. So in a given notebook, you probably want to run both async and sync processes, which at the moment requires either creating two client instances, or changing the internal state mid-way.
> 
> Could a more elegant option be to use a `with` statement ? E.g.
> 
> ```
> wps = WPSClient(url)
> with wps.options(output_format={}, mode="async"):
>     wps.my_process(input1=...)
> ```

Can we make the `with` statement optional? In the [rooki](https://github.com/roocs/rooki) client we init a birdy behind the scenes with a url and a mode (usually async). Then we call the methods generated for the processes:
```
from rooki import rooki
rooki.subset()
```
See example notebook:
https://nbviewer.jupyter.org/github/roocs/rooki/blob/master/notebooks/demo/demo-rooki-subset-by-time.ipynb 

And an example with more options:
https://nbviewer.jupyter.org/github/roocs/rooki/blob/master/notebooks/demo/demo-rooki-advanced.ipynb

As an alternative to `with` one could add optional parameters (`mode`, `outputs`) to the process methods:
```
rooki.subset(collection='cmip5.tas', time='1850-01-01/2008-12-30', mode='async', outputs=('output', ))
```
In this case those parameters would not be allowed to be used in process definition.

2020-10-08 18:33 UTC, cehbrecht commented
In the current `rooki` implementation the response of a WPS request is wrapped in a `Result` object to retrieve only the metalink output and provide some convenient methods to access it:
https://github.com/roocs/rooki/blob/88d3d741219940b7cdf44e7b60138310e5ad4d02/rooki/client.py#L36

Maybe the WPS execution could also be wrapped to provide additional parameters?
```
result = wps.subset(collection="tas")
result.compute(mode="async", outputs=("output", ))
print(result.outputs.output)
```

2020-10-08 18:45 UTC, huard commented
Yes, the `with` statement would only be used if you wanted to change defaults. 
I'm hesitant to shadow input argument names with the client's option. I would like to avoid this as much as possible. 

@f-PLT  I think the `output_format` dictionary needs to be nested: `{process_id: {input_id: format}}` if we want to call multiple processes inside the `with` and avoid clashes between outputs sharing the same name.

2020-10-08 19:16 UTC, f-PLT commented
For know, the changes I made make the `output_formats` argument an input for each process, both cli and client. 

It's self-contained as is, with each process needing it's own argument assignment if the outputs need to be customized (else everything runs like before, using the default values)

```
custom_format = {
    output_identifier1:{
        ...
    },
    ...
}
wps.process1(output_formats=custom_format, input1, ...)
wps.process2(output_formats=custom_format, input1, ...)
```
As for the refactor needed for the `with` statement, I think it's a bit out of scope of this PR and I'd need to clear it with David Byrns first.

2020-10-08 20:02 UTC, huard approved these changes
Looks good!  
I guess we're just missing a process to confirm it works as expected ?

2020-10-13 17:21 UTC, huard commented
Approved.

2020-11-17 13:25 UTC, huard commented
@cehbrecht Ok to merge ?

2020-11-17 16:07 UTC, cehbrecht approved these changes

2020-11-17 16:10 UTC, cehbrecht commented
@f-PLT @huard approved. Feel free to merge. Tests are failing due to the broken notebook in the `demo` folder. We can fix this with another PR ... or move the broken notebook to the `examples` folder.

2020-11-17 16:12 UTC, merged

2020-11-17 16:12 UTC, huard commented
Ok thanks !